pipeline{
    agent any

    tools{
        maven 'maven'
    }
    stages{
        stage("Build"){
            steps{
                sh "mvn clean install"
            }
        }
        stage("build & SonarQube analysis") {
          node {
              withSonarQubeEnv(installationName: "sonarqube" credentialsId: "sonarqube") {
                 sh 'mvn clean package sonar:sonar'
              }
          }
      }
    }
}
