pipeline{
    agent any

    tools{
        maven 'maven'
    }
    stages{
        stage("Build"){
            steps{
                sh "mvn clean install"
            }
        }
        stage("SonarQube Analysis"){
            steps{
                script{
                    withSonarQubeEnv(installationName: 'sonarqube', credentialsId: 'sonarqube') {
                    sh "mvn clean package sonar:sonar"
                }
            }
        }
    }
}
}
