pipeline{
    agent any

    tools{
        maven 'maven'
    }
    stages{
        stage("Maven version"){
            steps{
                sh "mvn --version"
            }
        }
        stage("Build"){
            steps{
                sh "mvn clean install"
            }
        }
    }
}
